WITH MEMBER_RANK AS
(
    SELECT 
          MEMBER_ID
        , RANK() OVER (ORDER BY COUNT(*) DESC) AS RNK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
SELECT
      MP.MEMBER_NAME
    , RR.REVIEW_TEXT
    , DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_RANK AS MR
    JOIN REST_REVIEW AS RR ON MR.MEMBER_ID = RR.MEMBER_ID
    JOIN MEMBER_PROFILE AS MP ON MR.MEMBER_ID = MP.MEMBER_ID
WHERE MR.RNK = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT
;
