SELECT
      YEAR(SALES_DATE) AS YEAR
    , MONTH(SALES_DATE) AS MONTH
    , U.GENDER AS GENDER
    , COUNT(DISTINCT U.USER_ID) AS USERS
FROM ONLINE_SALE AS S
    JOIN USER_INFO AS U ON S.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), U.GENDER
ORDER BY 1, 2, 3
;
