WITH CH_CNT AS
(
    SELECT 
          PARENT_ID AS ID
        , COUNT(*) OVER (PARTITION BY PARENT_ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
SELECT
      DISTINCT D.ID
    , COALESCE(C.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS D
    LEFT JOIN CH_CNT AS C ON D.ID = C.ID
ORDER BY 1
;
