WITH RECURSIVE ECOLI_GEN_DATA AS
(
    SELECT 
          ID
        , 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT
          E.ID
        , EG.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS E
        JOIN ECOLI_GEN_DATA AS EG ON E.PARENT_ID = EG.ID
),
ECOLI_CHILD_DATA AS (
    SELECT
          A.ID
        , COUNT(B.ID) AS CHILD_CNT
    FROM ECOLI_DATA AS A
        LEFT JOIN ECOLI_DATA AS B ON A.ID = B.PARENT_ID
    GROUP BY A.ID
)
SELECT
      COUNT(G.ID) AS COUNT
    , GENERATION
FROM ECOLI_GEN_DATA AS G
    LEFT JOIN ECOLI_CHILD_DATA AS C ON G.ID = C.ID
WHERE C.CHILD_CNT = 0
GROUP BY GENERATION
ORDER BY GENERATION
;
