WITH LEN_RANK AS (
    SELECT
          ID
        , FISH_TYPE
        , LENGTH
        , ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RK
    FROM FISH_INFO
)
SELECT 
      ID
    , N.FISH_NAME
    , LENGTH
FROM LEN_RANK AS R
    JOIN FISH_NAME_INFO AS N ON R.FISH_TYPE = N.FISH_TYPE
WHERE RK = 1
ORDER BY 1
;
