SELECT
      O.ID
    , O.GENOTYPE
    , P.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS O
    JOIN ECOLI_DATA AS P ON O.PARENT_ID = P.ID
WHERE (O.GENOTYPE & P.GENOTYPE) = P.GENOTYPE
ORDER BY O.ID
;
