WITH CALC_RANK AS 
(
    SELECT 
          *
        , ROW_NUMBER() OVER (PARTITION BY CATEGORY 
                             ORDER BY PRICE DESC
                             ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
          ) AS MAX_RANK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
)
SELECT 
    CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM CALC_RANK
WHERE MAX_RANK = 1
ORDER BY 2 DESC
;

