WITH COND_CODE AS (
    SELECT
          SUM(CASE WHEN NAME = 'Python'
              THEN CODE END) AS CODE_PY
        , SUM(CASE WHEN NAME = 'C#'
              THEN CODE END) AS CODE_CS
        , SUM(CASE WHEN CATEGORY = 'Front End' 
              THEN CODE END) AS CODE_FE
    FROM SKILLCODES
)
SELECT
      CASE WHEN (SKILL_CODE & CODE_PY AND SKILL_CODE & CODE_FE) THEN 'A'
           WHEN (SKILL_CODE & CODE_CS) THEN 'B'
           WHEN (SKILL_CODE & CODE_FE) THEN 'C'
      END AS GRADE
    , ID
    , EMAIL
FROM DEVELOPERS, COND_CODE
WHERE (SKILL_CODE & CODE_FE)
   OR (SKILL_CODE & CODE_CS)
ORDER BY 1, 2
;
