WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1 
    FROM HOURS
    WHERE HOUR < 23
)
SELECT 
      HOUR
    , COUNT(ANIMAL_ID) AS COUNT
FROM HOURS AS H
    LEFT JOIN ANIMAL_OUTS AS O ON H.HOUR = HOUR(O.DATETIME)    
GROUP BY HOUR
ORDER BY HOUR
;
