WITH TRUCK_HISTORY AS (
    SELECT 
          HISTORY_ID
        , DAILY_FEE
        , CAR.CAR_TYPE
        , DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DAYS
        , CASE WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90
                THEN '90일 이상'
           WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 30
                THEN '30일 이상'
           WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 7
                THEN '7일 이상'
           ELSE '해당 없음'
          END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
        JOIN CAR_RENTAL_COMPANY_CAR AS CAR ON HIS.CAR_ID = CAR.CAR_ID
    WHERE CAR.CAR_TYPE = '트럭'
)
SELECT 
      HISTORY_ID
    , TRUNCATE(RENT_DAYS * DAILY_FEE * (100 - COALESCE(PLAN.DISCOUNT_RATE, 0)) / 100, 0) AS FEE
FROM TRUCK_HISTORY AS HIS
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN 
      ON HIS.DURATION_TYPE = PLAN.DURATION_TYPE AND HIS.CAR_TYPE = PLAN.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC
;
