WITH UNAVAILABLE_CARS AS 
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE(START_DATE) <= '2022-10-16'
      AND DATE(END_DATE) >= '2022-10-16'
)
SELECT
      DISTINCT CAR_ID
    , CASE WHEN CAR_ID IN (SELECT * FROM UNAVAILABLE_CARS) THEN '대여중'
           ELSE '대여 가능'
      END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC
;
