WITH TARGET_SKILLS AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
)
SELECT 
      DISTINCT ID
    , EMAIL
    , FIRST_NAME
    , LAST_NAME
FROM DEVELOPERS AS DEV
    JOIN TARGET_SKILLS AS SKILL ON DEV.SKILL_CODE & SKILL.CODE
ORDER BY ID
;
