WITH C AS (
    SELECT 
          MAX(BOARD_ID) OVER (ORDER BY VIEWS DESC) AS BOARD_ID
        , MAX(VIEWS) OVER (ORDER BY VIEWS DESC) AS MAX_VIEWS
    FROM USED_GOODS_BOARD
    LIMIT 1
)
SELECT 
    CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS B
    JOIN C AS C ON B.BOARD_ID = C.BOARD_ID AND B.VIEWS = C.MAX_VIEWS
    JOIN USED_GOODS_FILE AS F ON C.BOARD_ID = F.BOARD_ID
ORDER BY F.FILE_ID DESC
;
