SELECT 
      AP.APNT_NO
    , PT.PT_NAME
    , AP.PT_NO
    , AP.MCDP_CD
    , DT.DR_NAME
    , AP.APNT_YMD
FROM APPOINTMENT AS AP
    JOIN PATIENT AS PT ON AP.PT_NO = PT.PT_NO
    JOIN DOCTOR AS DT ON AP.MDDR_ID = DT.DR_ID
WHERE DATE_FORMAT(AP.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
  AND AP.APNT_CNCL_YN = 'N'
  AND AP.MCDP_CD = 'CS'
ORDER BY AP.APNT_YMD
;
