WITH UNAVAILBLE_CARS AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE BETWEEN '2022-11-01' AND '2022-11-30'
       OR (START_DATE <= '2022-11-30' AND END_DATE > '2022-11-30')
)
SELECT
      CAR_ID
    , CAR.CAR_TYPE
    , TRUNCATE(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN 
        ON CAR.CAR_TYPE = PLAN.CAR_TYPE AND PLAN.DURATION_TYPE = '30일 이상'
WHERE CAR.CAR_TYPE IN ('세단', 'SUV')
  AND CAR.CAR_ID NOT IN (SELECT * FROM UNAVAILBLE_CARS WHERE CAR_ID IS NOT NULL)
  AND 500000 <= TRUNCATE(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100, 0) 
  AND 2000000 > TRUNCATE(DAILY_FEE * 30 * (100 - DISCOUNT_RATE) / 100, 0) 
ORDER BY 3 DESC, 2 ASC, 1 DESC
;
