WITH RECURSIVE THIRD_GEN AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, T.GEN + 1 AS GEN
    FROM ECOLI_DATA AS E
        JOIN THIRD_GEN AS T ON E.PARENT_ID = T.ID
    WHERE GEN < 3
)
SELECT ID
FROM THIRD_GEN
WHERE GEN = 3
ORDER BY ID
;

# WITH 
# FIRST_GEN AS (
#     SELECT ID
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IS NULL
# ),
# SECOND_GEN AS (
#     SELECT ID
#     FROM ECOLI_DATA
#     WHERE PARENT_ID IN (SELECT * FROM FIRST_GEN)
# )
# SELECT ID
# FROM ECOLI_DATA
# WHERE PARENT_ID IN (SELECT * FROM SECOND_GEN)
# ORDER BY 1
