WITH TEMP AS (
    SELECT 
        CITY,
        LENGTH(CITY) AS CITY_LEN,
        ROW_NUMBER() OVER (PARTITION BY LENGTH(CITY) ORDER BY CITY) AS GROUP_RANK,
        MIN(LENGTH(CITY)) OVER () AS CITY_MIN,
        MAX(LENGTH(CITY)) OVER () AS CITY_MAX
    FROM STATION
)
SELECT
    CITY,
    CITY_LEN
FROM TEMP
WHERE GROUP_RANK = 1
  AND (CITY_LEN = CITY_MIN
       OR CITY_LEN = CITY_MAX)
;
