WITH RANKED_LAT AS (
    SELECT
        LAT_N,
        ROW_NUMBER() OVER (ORDER BY LAT_N) AS RANKING,
        COUNT(*) OVER () AS TOTAL_COUNT
    FROM STATION
)
SELECT
    ROUND(AVG(LAT_N), 4)
FROM RANKED_LAT
WHERE RANKING = FLOOR((TOTAL_COUNT+1) / 2)
   OR RANKING = CEILING((TOTAL_COUNT+1) / 2)
;
